### ISSUE TITLE
Issue with unc0ver

### ISSUE THREAD

**Issue by kitkatclap** [Karimo299/DontKillMyMusic#2]
Hi, I am on the latest unc0ver jailbreak v 1.0.3. I am on iPhone X iOS 11.4b3. The tweak was working perfectly with Electra, but now does not work. The latest version of the tweak gives me the error, failed to load preference bundle. Previous versions do not work- I can still close the music app, and also causes a glitch where in the app switcher, running apps can not be switched to. I can only get to them with gestures or the app on the home screen. I restored the root file system so I am sure the issue is not due to my setup or from switching jailbreaks.

**Comment by Karimo299** [comment]
Try downloading preferencesloader and applist

**Comment by kitkatclap** [comment]
Preferenceloader was installed, applist wasn’t. Applist fixed it, thank you. Maybe make applist a requisite tweak so it automatically installs? Thank you again!

**Comment by Karimo299** [comment]
Done
